import type { Metadata, Viewport } from "next";
import "./globals.scss";

import { Inter } from "next/font/google";

import { Bar } from "@/components/shared/Bar/Bar";
import { Footer } from "@/components/shared/Footer/Footer";
import { Gradient } from "@/components/shared/Gradient/Gradient";
import { Header } from "@/components/shared/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  width: "device-width",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Bar />
        <Header />
        {children}
        <Footer />
        <Gradient className={"gradient1"} />
        <Gradient className={"gradient2"} />
      </body>
    </html>
  );
}
